/*
 * Copyright 2019 Stephen Davies
 *
 * This file is part of eagle2nc.
 *
 * eagle2nc is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * eagle2nc is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with eagle2nc. If not, see <https://www.gnu.org/licenses/>.
 */

package com.github.aushacker.eagle2nc.nc;

import java.io.PrintStream;

/**
 * @author Stephen Davies
 * @since March 2019
 */
public class Generator {

	private static final String TEST_FILE = "data/astable_555.brd";

	//private static final double DEFAULT_CLEARANCE = 1.0;

	private PrintStream out;

	private ZStrategy zStrategy;

	private Generator(String file, ZStrategy zStrategy) {
		this.out = System.out;
		this.zStrategy = zStrategy;
	}

	public static void main(String[] args) {
		Generator gen = new Generator(TEST_FILE, new SolenoidStrategy());

		gen.generate();
	}

	private void generate() {
		// TODO setOutputFile();
		preamble();
		zStrategy.toolChange(out);
	}

	/**
	 * Common setup commands used by all jobs.
	 */
	private void preamble() {
		out.println("( Generated by eagle2nc )");
		out.println("( " + " )");
		out.println("G90 ( absolute )");
		out.println("G21 ( mm )");
		out.println("G94 ( per minute )");
		out.println("G17 ( xy plane )");
	}

}
